services:
  oracle-fisher:
    build: .
    container_name: oracle_fisher
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./accounts.json:/app/accounts.json
      - ./oci_keys:/root/.oci
    environment:
      LOG_FORMAT: "json"
      NO_COLOR: "1"
      APP_ENV: "production"
      LOG_LEVEL: "info"
      OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING: "True"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"